# Introduction to TensorFlow


<H4> What we're going to cover :

* Introduction to tensors (creating tensors)
* Getting information from tensors (tensor attributes)
* Manipulating tensors (tensor operations)
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow
* Exercises to try




<h4> 1) Introduction to Tensors

---


If you've ever used NumPy, tensors are kind of like NumPy arrays (we'll see more on this later).

For the sake of this notebook and going forward, you can think of a tensor as a multi-dimensional numerical representation (also referred to as n-dimensional, where n can be any number) of something. Where something can be almost anything you can imagine:

It could be numbers themselves (using tensors to represent the price of houses).
It could be an image (using tensors to represent the pixels of an image).
It could be text (using tensors to represent words).
Or it could be some other form of information (or data) you want to represent with numbers.
The main difference between tensors and NumPy arrays (also an n-dimensional array of numbers) is that tensors can be used on GPUs (graphical processing units) and TPUs (tensor processing units).

The benefit of being able to run on GPUs and TPUs is faster computation, this means, if we wanted to find patterns in the numerical representations of our data, we can generally find them faster using GPUs and TPUs.

Okay, we've been talking enough about tensors, let's see them.

The first thing we'll do is import TensorFlow under the common alias tf.


In [1]:
# Import Tensorflow 
import tensorflow as tf

<h5> Creating Tensors with tf.constant()

In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

A scalar is known as a rank 0 tensor. Because it has no dimensions (it's just a number).

In [3]:
vector = tf.constant([1,2,3])
print(vector)
vector.ndim

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


1

In [4]:
matrix = tf.constant([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
print(matrix)
matrix.ndim

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


2

In [5]:
tensor = tf.constant([[[1,2,3,4],
                       [5,6,7,8]],
                      
                      [[4,3,1,3],
                       [4,2,1,5]],
                      
                      [[6,7,4,2],
                       [6,4,2,1]]])
print(tensor)
tensor.ndim

tf.Tensor(
[[[1 2 3 4]
  [5 6 7 8]]

 [[4 3 1 3]
  [4 2 1 5]]

 [[6 7 4 2]
  [6 4 2 1]]], shape=(3, 2, 4), dtype=int32)


3


This is known as a rank 3 tensor (3-dimensions), however a tensor can have an arbitrary (unlimited) amount of dimensions.

For example, you might turn a series of images into tensors with shape (224, 224, 3, 32), where: 224, 224 (the first 2 dimensions) are the height and width of the images in pixels.
3 is the number of colour channels of the image (red, green blue).
32 is the batch size (the number of images a neural network sees at any one time).
All of the above variables we've created are actually tensors. But you may also hear them referred to as their different names (the ones we gave them):
<br>

* scalar: a single number.<br>
* vector: a number with direction (e.g. wind speed with direction).<br>
* matrix: a 2-dimensional array of numbers.<br>
* tensor: an n-dimensional arrary of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector).

### Creating Tensors with tf.Variable()




* You can also (although you likely rarely will, because often, when working with data, tensors are created for you automatically) create tensors using tf.Variable().

* The difference between tf.Variable() and tf.constant() is tensors created with tf.constant() are immutable (can't be changed, can only be used to create a new tensor), where as, tensors created with tf.Variable() are mutable (can be changed).

In [6]:
changable_tensor = tf.Variable(([3,4],
                               [2,5]))
unchangable_tensor = tf.constant(([1,5],
                                 [2,3]))
changable_tensor[0].assign([1,2])
changable_tensor

# Note: You can't manipulate unchangable_tensor's value becuase its initialized using tf.constant()

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [2, 5]], dtype=int32)>

### Creating random tensors with tf.random()



-> Random tensors are tensors of some abitrary size which contain random numbers.

(?) Why would you want to create random tensors?

This is what neural networks use to intialize their weights (patterns) that they're trying to learn in the data.

For example, the process of a neural network learning often involves taking a random n-dimensional array of numbers and refining them until they represent some kind of pattern (a compressed way to represent the original data).


In [7]:
# Creating a random tensor generator
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal([3,4])
random_1

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
       [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
      dtype=float32)>

In [8]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal([3,4])

random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal([3,4])

random_2, random_3



(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ,  0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284,  0.1480774 , -0.23362993]],
       dtype=float32)>)


The random tensors we've made are actually pseudorandom numbers (they appear as random, but really aren't).

If we set a seed we'll get the same random numbers (if you've ever used NumPy, this is similar to np.random.seed(42)).

Setting the seed says, "hey, create some random numbers, but flavour them with X" (X is the seed).



### What if you wanted to shuffle the order of a tensor? shuffle with tf.random.shuffle()

<b>Wait, why would you want to do that?</b>


Let's say you working with 15,000 images of cats and dogs and the first 10,000 images of were of cats and the next 5,000 were of dogs. This order could effect how a neural network learns (it may overfit by learning the order of the data), instead, it might be a good idea to move your data around.

In [9]:
# Shuffle a tensor
not_shuffled = tf.constant([[1,2],
                            [3,4],
                            [5,6]])
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled),tf.random.shuffle(not_shuffled),tf.random.shuffle(not_shuffled,seed=42)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 4],
        [5, 6],
        [1, 2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[5, 6],
        [1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

<h3> 
Wait... why didn't the numbers come out the same?

It's due to rule #4 of the tf.random.set_seed() documentation.

"4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

tf.random.set_seed(42) sets the global seed, and the seed parameter in tf.random.shuffle(seed=42) sets the operation seed.

Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed."

<h2>• Other ways to make tensors

Though you might rarely use these (remember, many tensor operations are done behind the scenes for you), you can use tf.ones() to create a tensor of all ones and tf.zeros() to create a tensor of all zeros.

In [10]:
# makes tensor all one's
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [11]:
# make tensor all zero's
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>


You can also turn NumPy arrays in into tensors.

Remember, the main difference between tensors and NumPy arrays is that tensors can be run on GPUs.

>🔑 **NOTE:** A matrix or tensor is typically represented by a capital letter (e.g. X or A) where as a vector is typically represented by a lowercase letter (e.g. y or b).

In [12]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[2, 6, 2]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 6, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10],
         [11, 12]],
 
        [[13, 14],
         [15, 16],
         [17, 18],
         [19, 20],
         [21, 22],
         [23, 24]]], dtype=int32)>)

# <h2><b>Getting information from tensors (shape, rank, size)</b>

There will be times when you'll want to get different pieces of information from your tensors, in particuluar, you should know the following tensor vocabulary:



* **Shape:** The length (number of elements) of each of the dimensions of a tensor.<br><br>
* **Rank:** The number of tensor dimensions. A scalar has rank 0, a **vector:** has rank 1, a matrix is rank 2, a tensor has rank n.<br><br>
* **Axis or Dimension:** A particular dimension of a tensor.<br><br>
* **Size:** The total number of items in the tensor.
You'll use these especially when you're trying to line up the shapes of your data to the shapes of your model. For example, making sure the shape of your image tensors are the same shape as your models input layer.

We've already seen one of these before using the ndim attribute. Let's see the rest.

In [13]:
# Create a rank 4 tensor

rank_4_tensor = tf.zeros([2,2,3,4])
rank_4_tensor

<tf.Tensor: shape=(2, 2, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [14]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)  
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0]) # as its (2, 2, 3, 4) [0] would be 2 & [-1] would be 4
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 2, 3, 4)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 4
Total number of elements (2*3*4*5): 48


<h5> You can also index tensors just like Python lists.

In [15]:
# Get the first 2 items of each dimension
print(rank_4_tensor[:2, :2, :2, :2])
rank_4_tensor[...,-1]

tf.Tensor(
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]], shape=(2, 2, 2, 2), dtype=float32)


<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [16]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=array([[[[0., 0., 0., 0.]]]], dtype=float32)>

In [17]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.random.normal([2,2])
print(rank_2_tensor)

# Get the last item of each row
rank_2_tensor[:, -1]

tf.Tensor(
[[-0.55909735 -0.5347214 ]
 [ 2.3730333  -1.5725931 ]], shape=(2, 2), dtype=float32)


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.5347214, -1.5725931], dtype=float32)>

<h5> You can also add dimensions to your tensor whilst keeping the same information present using tf.newaxis.



In [18]:
# Add an extra dimension (to the end)
rank_3_tensor = rank_2_tensor[...,tf.newaxis] # method 1
rank_3_tensor

tf.expand_dims(rank_2_tensor, 0) # method 2


<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[-0.55909735, -0.5347214 ],
        [ 2.3730333 , -1.5725931 ]]], dtype=float32)>

### Basic operations
You can perform many of the basic mathematical operations directly on tensors using Pyhton operators such as, +, -, *.





In [19]:
# You can add values to a tensor using the addition operator
tensor1 = tf.constant([[10, 7], [3, 4]])
tf.multiply(tensor1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

Since we used tf.constant(), the original tensor is unchanged (the addition gets done on a copy).



In [20]:
# Original tensor unchanged
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

Other operators also work.



In [21]:
# Multiplication (known as element-wise multiplication)
tensor1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [22]:
# Subtraction
tensor1 - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

You can also use the equivalent TensorFlow function. Using the TensorFlow function (where possible) has the advantage of being sped up later down the line when running as part of a TensorFlow graph.



In [23]:
tf.multiply(tensor1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

###<h2><b> Matrix mutliplication</b>



Matrix mutliplication

One of the most common operations in machine learning algorithms is matrix multiplication.

TensorFlow implements this matrix multiplication functionality in the tf.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:<br>
(3, 5) @ (3, 5) won't work<br>
(5, 3) @ (3, 5) will work<br>
(3, 5) @ (5, 3) will work<br><br>
The resulting matrix has the shape of the outer dimensions:<br>
(5, 3) @ (3, 5) -> (5, 5)<br>
(3, 5) @ (5, 3) -> (3, 3)<br>
> 🔑 Note: '@' in Python is the symbol for matrix multiplication.

In [24]:
# Matrix multiplication in TensorFlow
print(tensor1)
tf.matmul(tensor1, tensor1)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [25]:
# Matrix multiplication with Python operator '@'
tensor1 @ tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [26]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)


Trying to matrix multiply two tensors with the shape (3, 2) errors because the inner dimensions don't match.

We need to either:

Reshape X to `(2, 3)` so it's `(2, 3) @ (3, 2)`.<br>
Reshape Y to `(3, 2)` so it's `(3, 2) @ (2, 3)`.
We can do this with either:

`tf.reshape()` - allows us to reshape a tensor into a defined shape. 
`tf.transpose()` - switches the dimensions of a given tensor.

Let's try tf.reshape() first.



In [27]:
# Example of reshape (3, 2) -> (2, 3)
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [28]:
# Try matrix multiplication with reshaped Y
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [29]:
# Example of transpose (3, 2) -> (2, 3)
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [30]:
# Try matrix multiplication 
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [31]:
# You can achieve the same result with parameters
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

<h2>The dot product

Multiplying matrices by eachother is also referred to as the dot product.

You can perform the `tf.matmul()` operation using `tf.tensordot()`.

In [32]:
# Perform the dot product on X and Y (requires X to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

### Changing the datatype of a tensor


Changing the datatype of a tensor

Sometimes you'll want to alter the default datatype of your tensor.

This is common when you want to compute using less precision (e.g. 16-bit floating point numbers vs. 32-bit floating point numbers).

Computing with less precision is useful on devices with less computing capacity such as mobile devices (because the less bits, the less space the computations require).

You can change the datatype of a tensor using `tf.cast()`.

In [33]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])

# Create a new tensor with default datatype (int32)
C = tf.constant([1, 7])
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>)

In [34]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [35]:
# Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

<h4>Getting the absolute value

Sometimes you'll want the absolute values (all values are positive) of elements in your tensors.

To do so, you can use `tf.abs()`.

In [36]:
# Create tensor with negative values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [37]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>


###Finding the min, max, mean, sum (aggregation)

You can quickly aggregate (perform a calculation on a whole tensor) tensors to find things like the minimum value, maximum value, mean and sum of all the elements.

To do so, aggregation methods typically have the syntax reduce()_[action], such as:

* `tf.reduce_min()` - find the minimum value in a tensor.<br>
* `tf.reduce_max()` - find the maximum value in a tensor  (helpful for when you want to find the highest prediction probability).<br>
* `tf.reduce_mean()` - find the mean of all elements in a tensor.<br>
* `tf.reduce_sum()` - find the sum of all elements in a tensor.<br>

<b>Note:</b> typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().
Let's see them in action.

In [38]:
import numpy as np
tensor = tf.constant(np.random.randint(0,10, size=50))

print("Minimum : ", tf.reduce_min(tensor))
print("Max : ", tf.reduce_max(tensor))
print("Mean : ", tf.reduce_mean(tensor))
print("Sum : ", tf.reduce_sum(tensor))


Minimum :  tf.Tensor(0, shape=(), dtype=int64)
Max :  tf.Tensor(9, shape=(), dtype=int64)
Mean :  tf.Tensor(4, shape=(), dtype=int64)
Sum :  tf.Tensor(228, shape=(), dtype=int64)


###Finding the positional maximum and minimum

How about finding the position a tensor where the maximum value occurs?

This is helpful when you want to line up your labels (say `['Green', 'Blue', 'Red']`) with your prediction probabilities tensor (e.g. `[0.98, 0.01, 0.01]`).

In this case, the predicted label (the one with the highest prediction probability) would be `'Green'`.

You can do the same for the minimum (if required) with the following:

* `tf.argmax()` - find the position of the maximum element in a given tensor.
* `tf.argmin()` - find the position of the minimum element in a given tensor.

In [39]:
tensor = tf.constant(np.random.randint(0,10,size=10))
tensor,tf.argmin(tensor), tf.argmax(tensor)

(<tf.Tensor: shape=(10,), dtype=int64, numpy=array([4, 6, 5, 1, 3, 3, 1, 8, 6, 3])>,
 <tf.Tensor: shape=(), dtype=int64, numpy=3>,
 <tf.Tensor: shape=(), dtype=int64, numpy=7>)

###Squeezing a tensor (removing all single dimensions)

If you need to remove single-dimensions from a tensor (dimensions with size 1), you can use tf.squeeze().

`tf.squeeze()` - remove all dimensions of 1 from a tensor.

In [ ]:
tensor = tf.constant(np.random.randint(0,100,size=50), shape = (1,1,1,1,50))
tf.squeeze(tensor)

###One-hot encoding

If you have a tensor of indicies and would like to one-hot encode it, you can use `tf.one_hot()`.

You should also specify the depth parameter (the level which you want to one-hot encode to).

In [40]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# One hot encode them
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

You can also specify values for on_value and off_value instead of the default 0 and 1.



In [41]:
# Specify custom values for on and off encoding
tf.one_hot(some_list, depth=4, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!"]], dtype=object)>


###Squaring, log, square root

Many other common mathematical operations you'd like to perform at some stage, probably exist.

Let's take a look at:

* `tf.square()` - get the square of every value in a tensor.
* `tf.sqrt()` - get the squareroot of every value in a tensor (note: the elements need to be floats or this will error).<br>
* `tf.math.log()` - get the natural log of every value in a tensor (elements need to floats).

In [45]:
H = tf.range(1,10)

# Square it
tf.square(H)

# Find the squareroot (will error), needs to be non-integer
# tf.sqrt(H)

H = tf.cast(H, dtype=float)
tf.sqrt(H)

# Find the log (input also needs to be float)
tf.math.log(H)



<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>


###Manipulating tf.Variable tensors

Tensors created with tf.Variable() can be changed in place using methods such as:

* `.assign()` - assign a different value to a particular index of a variable tensor.
* `.add_assign()` - add to an existing value and reassign it at a particular index of a variable tensor.

In [50]:
# Create a variable tensor
I = tf.Variable(np.arange(0, 5))

# Assign the final value a new value of 50
I.assign([0, 1, 2, 3, 50])

# Add 10 to every element in I
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>


###Using `@tf.function`

In your TensorFlow adventures, you might come across Python functions which have the decorator `@tf.function`.

If you aren't sure what Python decorators do, read RealPython's guide on them.

But in short, decorators modify a function in one way or another.

In the `@tf.function` decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with `@tf.function`, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

For more on this, read the Better performnace with tf.function guide.

In [ ]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

In [ ]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)


If you noticed no difference between the above two functions (the decorated one and the non-decorated one) you'd be right.

Much of the difference happens behind the scenes. One of the main ones being potential code speed-ups where possible.

# <b>---------- END OF INTRO TO TENSORFLOW ----------</b>